version: '3.8'

services:
  onedep:
    # command: cp /etc/httpd/sites-enabled/* /etc/httpd/conf.d/ && /usr/sbin/httpd -D FOREGROUND
    image: onedep
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CS_USER: ${CS_USER}
        CS_PW: ${CS_PW}
        CS_URL: ${CS_URL}
    environment:
      WWPDB_SITE_ID: ${WWPDB_SITE_ID}
      WWPDB_SITE_LOC: ${WWPDB_SITE_LOC}
      PYTHONPATH: "/env:/venv"
      TOP_DATA_DIR: /data
      TOP_WWPDB_SESSIONS_PATH: /data/sessions/sessions
    ports:
      - target: 80
        published: 12000
    volumes:
      - onedep_data:/data
      - type: bind
        source: ./env/site-config
        target: /env
      - type: bind
        source: ./env/apache
        target: /etc/httpd/sites-enabled

volumes:
  onedep_data:

