version: '3.8'

services:
  onedep:
    entrypoint: /bin/sh
    image: onedep
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CS_USER: ${CS_USER}
        CS_PW: ${CS_PW}
        CS_URL: ${CS_URL}
    environment:
      WWPDB_SITE_ID: ${WWPDB_SITE_ID}
      WWPDB_SITE_LOC: ${WWPDB_SITE_LOC}
      PYTHONPATH: "/env:/venv"
    ports:
      - target: 8080
        published: 8080
    volumes:
      - onedep_data:/data
      - type: bind
        source: ./env
        target: /env

volumes:
  onedep_data:

