version: '3.8'

services:
  onedep:
    # command: cp /etc/httpd/sites-enabled/* /etc/httpd/conf.d/ && /usr/sbin/httpd -D FOREGROUND
    image: onedep
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CS_USER: ${CS_USER}
        CS_PW: ${CS_PW}
        CS_URL: ${CS_URL}
    environment:
      WWPDB_SITE_ID: ${WWPDB_SITE_ID}
      WWPDB_SITE_LOC: ${WWPDB_SITE_LOC}
      PYTHONPATH: "/env:/venv"
      TOP_DATA_DIR: /data
      TOP_WWPDB_SESSIONS_PATH: /data/sessions/sessions
      MOGULPATH: /data/csd
    # depends_on:
    #  - db
    ports:
      - target: 80
        published: 12000
    volumes:
      - onedep_data:/data
      - type: bind
        source: ./env/site-config
        target: /env
      - type: bind
        source: ./env/apache
        target: /etc/httpd/sites-enabled
        
  # database - mysql database
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password  --bind-address=0.0.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      #MYSQL_DATABASE: depui_django
    ports:
      - target: 3306
        published: 3306
    volumes:
        - ./env/db:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8181

  # message broker - used for APIs
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RMQ_VHOST}
    ports:
      - 5672:5672
      - 5673:5673
      - 15672:15672

volumes:
  onedep_data:

