/*!50001 DROP VIEW IF EXISTS `dep_instance`*/;
CREATE OR REPLACE  VIEW `dep_instance` 
AS select 
`d`.`dep_set_id` AS `dep_set_id`,
`d`.`depPW` AS `deppw`,
`d`.`pdb_id` AS `pdb_id`,
`d`.`initial_deposition_date` AS `dep_initial_deposition_date`,
`d`.`annotator_initials` AS `annotator_initials`,
`d`.`deposit_site` AS `dep_deposit_site`,
`d`.`process_site` AS `dep_process_site`,
`d`.`status_code` AS `dep_status_code`,
`d`.`author_release_status_code` AS `dep_author_release_status_code`,
`d`.`title` AS `dep_title`,
`d`.`author_list` AS `dep_author_list`,
`d`.`exp_method` AS `dep_exp_method`,
`d`.`status_code_exp` AS `dep_status_code_exp`,
`d`.`SG_center` AS `dep_SG_center`,
`d`.`notify` AS `dep_notify`,
`d`.`locking` AS `dep_locking`,
`d`.`bmrb_id` AS `dep_bmrb_id`,
`d`.`emdb_id` AS `dep_emdb_id`,
`d`.`status_code_emdb` AS `dep_status_code_emdb`,
`d`.`status_code_bmrb` AS `dep_status_code_bmrb`,
`d`.`status_code_other` AS `dep_status_code_other`,
`d`.`post_rel_status` AS `dep_post_rel_status`,
`wfi`.`ordinal` AS `inst_ordinal`,
`wfi`.`wf_inst_id` AS `inst_id`,
`wfi`.`owner` AS `inst_owner`,
`wfi`.`inst_status` AS `inst_status`,
`wfi`.`status_timestamp` AS `inst_status_timestamp`,
`wfi`.`wf_class_id` AS `class_id`,
`wfcd`.`wf_class_name` AS `class_name`,
`wfcd`.`title` AS `class_title`,
`wfcd`.`author` AS `class_author`,
`wfcd`.`version` AS `class_version`,
`wfcd`.`class_file` AS `class_file` 
from ((`deposition` `d` join `wf_instance` `wfi`) join `wf_class_dict` `wfcd`) 
where ((`d`.`dep_set_id` = `wfi`.`dep_set_id`) and (`wfi`.`wf_class_id` = `wfcd`.`wf_class_id`));

CREATE OR REPLACE VIEW `dep_last_instance`
 AS (select 
   `deposition`.`dep_set_id` AS `dep_set_id`,
   `deposition`.`depPW` AS `deppw`,
   `deposition`.`pdb_id` AS `pdb_id`,
   `deposition`.`initial_deposition_date` AS `dep_initial_deposition_date`,
   `deposition`.`annotator_initials` AS `annotator_initials`,
   `deposition`.`deposit_site` AS `dep_deposit_site`,
   `deposition`.`process_site` AS `dep_process_site`,
   `deposition`.`status_code` AS `dep_status_code`,
   `deposition`.`author_release_status_code` AS `dep_author_release_status_code`,
   `deposition`.`title` AS `dep_title`,
   `deposition`.`author_list` AS `dep_author_list`,
   `deposition`.`exp_method` AS `dep_exp_method`,
   `deposition`.`status_code_exp` AS `dep_status_code_exp`,
   `deposition`.`SG_center` AS `dep_SG_center`,
   `deposition`.`notify` AS `dep_notify`,
   `deposition`.`locking` AS `dep_locking`,
   `deposition`.`bmrb_id` AS `dep_bmrb_id`,
   `deposition`.`emdb_id` AS `dep_emdb_id`,
   `deposition`.`status_code_emdb` AS `dep_status_code_emdb`,
   `deposition`.`status_code_bmrb` AS `dep_status_code_bmrb`,
   `deposition`.`status_code_other` AS `dep_status_code_other`,
   `deposition`.`post_rel_status` AS `dep_post_rel_status`,
   `wf_instance_last`.`ordinal` AS `inst_ordinal`,
   `wf_instance_last`.`wf_inst_id` AS `inst_id`,
   `wf_instance_last`.`owner` AS `inst_owner`,
   `wf_instance_last`.`inst_status` AS `inst_status`,
   `wf_instance_last`.`status_timestamp` AS `inst_status_timestamp`,
   `wf_instance_last`.`wf_class_id` AS `class_id`,
   `wf_class_dict`.`wf_class_name` AS `class_name`,
   `wf_class_dict`.`title` AS `class_title`,
   `wf_class_dict`.`author` AS `class_author`,
   `wf_class_dict`.`version` AS `class_version`,
   `wf_class_dict`.`class_file` AS `class_file`
from ((`deposition` join `wf_instance_last`) join `wf_class_dict`) 
where ((`deposition`.`dep_set_id` = `wf_instance_last`.`dep_set_id`) and (`wf_instance_last`.`wf_class_id` = `wf_class_dict`.`wf_class_id`)));
